# Add this file to 
# <blender path>/2.70/scripts/startup
# (or similar target path, adapt path below accordingly
# so that it points to the folder of files that are 
# generated by PythonArchitect)
#
# Then: after launching Blender, you can simply type "import generateCAD" 
# into python console, which will generate the full CAD file

import sys
sys.path.append('c:\\Users\\Sebastian\\Documents\\GrundRettenbach\\Hausplan_004\\PythonArchitect\\exampleHouse\\generatedFiles')
import generateCad
